# https://github.com/python-poetry/poetry/blob/main/.github/workflows/.tests-matrix.yaml
on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      python-version:
        required: true
        type: string
      run-mypy:
        required: true
        type: boolean
      run-pytest:
        required: true
        type: boolean
      run-pytest-export:
        required: true
        type: boolean
defaults:
  run:
    shell: bash

jobs:
  pytest:
    name: Lint & test
    runs-on: ${{ inputs.runner }}
    if: inputs.run-pytest
    steps:
      - uses: actions/checkout@v4
        with:
          python-version: ${{ inputs.python-version }}
      # TODO: install requirements once, and re-use the container.
      - run: |
          pip install -r requirements-dev.txt \
          && make lint \
          && make test
